### ISSUE TITLE
The script is not working

### ISSUE THREAD

**Issue by ripon-xeon** [AbdulRKB/Email-Spoofer#1]
This is not working. after submitting the form, the page is redirected to the google home page.

**Comment by AbdulRKB** [comment]
Hi, Thanks for Bringing my attention to this. 
I updated the tool but forgot to update the link in the `README.md` file.

The **latest version** of the script can be accessed by clicking [here](https://cntreon.000webhostapp.com/).

**Sorry for the inconvenience**

Please give further information if the tool doesn't work.
